// EN: The demo plays the investigation from start to end and writes what it found to results/.
//     1. Metrics: the 99th percentile says THAT requests are slow and in which services.
//     2. Traces: a TraceQL search finds one slow request, and its waterfall says WHERE.
//     3. Logs: the trace id finds the lines of that request, and one of them says WHY.
// PT: A demo percorre a investigação do começo ao fim e grava o que encontrou em results/.
//     1. Métricas: o percentil 99 diz QUE há requisições lentas e em quais serviços.
//     2. Traces: uma busca TraceQL acha uma requisição lenta, e a cascata dela diz ONDE.
//     3. Logs: o trace id acha as linhas daquela requisição, e uma delas diz POR QUÊ.
// ES: La demo recorre la investigación de principio a fin y graba lo que encontró en results/.
//     1. Métricas: el percentil 99 dice QUE hay peticiones lentas y en qué servicios.
//     2. Traces: una búsqueda TraceQL encuentra una petición lenta, y su cascada dice DÓNDE.
//     3. Logs: el trace id encuentra las líneas de esa petición, y una de ellas dice POR QUÉ.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readLabEnv, SLOW_SKU } from "./config";
import {
	checkout,
	eventually,
	fetchTrace,
	logsOfTraceQuery,
	lokiQuery,
	P99_QUERY,
	promQuery,
	SLOW_SPAN_QUERY,
	searchTraces,
	waitReady,
	waterfall,
} from "./lab";

const env = readLabEnv();
const resultsDir = join(env.PROJECT_DIR, "results");
mkdirSync(resultsDir, { recursive: true });

console.log("waiting for the back ends...");
await Promise.all([
	waitReady(`${env.TEMPO_URL}/ready`, 180_000),
	waitReady(`${env.LOKI_URL}/ready`, 180_000),
	waitReady(`${env.PROMETHEUS_URL}/-/ready`, 180_000),
]);

// EN: Mostly healthy traffic, with a few requests for the SKU that hits the slow dependency.
// PT: Tráfego quase todo saudável, com algumas requisições do SKU que cai na dependência lenta.
// ES: Tráfico casi todo sano, con algunas peticiones del SKU que cae en la dependencia lenta.
const skus = ["blue-pen", "red-pen", "notebook", "stapler", "desk-lamp"];
let slowTraceId = "";

// EN: A warm-up request, then a pause longer than the 5 s export interval. `rate()` measures
//     growth between two samples of a series, so each series must exist before the load.
// PT: Uma requisição de aquecimento, e depois uma pausa maior que o intervalo de exportação de
//     5 s. O `rate()` mede crescimento entre duas amostras de uma série, então cada série
//     precisa existir antes da carga.
// ES: Una petición de calentamiento, y luego una pausa mayor que el intervalo de exportación de
//     5 s. `rate()` mide crecimiento entre dos muestras de una serie, así que cada serie
//     debe existir antes de la carga.
await checkout(env.GATEWAY_URL, "blue-pen");
await Bun.sleep(8000);
for (let i = 0; i < 60; i++) {
	const slow = i % 12 === 5;
	const result = await checkout(env.GATEWAY_URL, slow ? SLOW_SKU : (skus[i % skus.length] ?? "blue-pen"));
	if (slow) {
		slowTraceId = result.traceId;
	}
}
console.log(`sent 60 requests, 5 of them for "${SLOW_SKU}"`);

const p99 = await eventually(
	async () => {
		const samples = await promQuery(env.PROMETHEUS_URL, P99_QUERY);
		return samples.length >= 3 && samples.every((sample) => Number.isFinite(sample.value)) ? samples : undefined;
	},
	300_000,
	"the p99 of the three services in Prometheus",
);

const found = await eventually(
	async () => {
		const traces = await searchTraces(env.TEMPO_URL, SLOW_SPAN_QUERY);
		return traces.some((trace) => trace.traceID === slowTraceId) ? traces : undefined;
	},
	300_000,
	"the slow trace in the Tempo search",
);
const trace = await fetchTrace(env.TEMPO_URL, slowTraceId);

const logQl = logsOfTraceQuery(slowTraceId);
const logs = await eventually(
	async () => {
		const lines = await lokiQuery(env.LOKI_URL, logQl);
		return lines.some((line) => line.severity === "WARN") ? lines : undefined;
	},
	300_000,
	"the log lines of the slow trace in Loki",
);

const p99Table = p99
	.sort((a, b) => (a.labels.service_name ?? "").localeCompare(b.labels.service_name ?? ""))
	.map((sample) => `| ${sample.labels.service_name} | ${sample.value.toFixed(3)} |`)
	.join("\n");
const logTable = logs
	.map((line) => `| ${line.service} | ${line.severity} | ${line.message} | ${line.fields.duration_ms ?? ""} |`)
	.join("\n");

const report = `# three-signals: one slow request, explained by three signals

Generated by \`docker compose run --rm demo\`. Load: 60 requests through the gateway, 5 of them for the SKU \`${SLOW_SKU}\`.

## 1. Metrics: is something slow, and in which service?

PromQL:

\`\`\`promql
${P99_QUERY}
\`\`\`

| service | p99 (s) |
| --- | --- |
${p99Table}

The three services are slow together, because each one waits for the next. The metric has no SKU label, so it cannot say which requests are slow.

## 2. Traces: where does the time go?

TraceQL:

\`\`\`traceql
${SLOW_SPAN_QUERY}
\`\`\`

Traces found: ${found.length}. One of them, \`${slowTraceId}\`:

\`\`\`text
${waterfall(trace.spans)}
\`\`\`

Every span above \`warehouse.lookup\` is long only because it waits. The self time column points at one span. Its attributes: \`${JSON.stringify(trace.spans.find((span) => span.name === "warehouse.lookup")?.attributes ?? {})}\`.

## 3. Logs: why?

LogQL:

\`\`\`logql
${logQl}
\`\`\`

| service | severity | message | duration_ms |
| --- | --- | --- | --- |
${logTable}
`;

writeFileSync(join(resultsDir, "results.md"), report);
writeFileSync(
	join(resultsDir, "slow-trace.json"),
	`${JSON.stringify({ traceId: slowTraceId, query: SLOW_SPAN_QUERY, search: found, spans: trace.spans, trace: trace.raw }, null, "\t")}\n`,
);
console.log(report);
console.log(`written: results/results.md and results/slow-trace.json (trace ${slowTraceId})`);
