-- EN: One small domain shared by the three API styles: an author has many books, a book has many
--     reviews. The two foreign keys are the "nested reads" that make the styles differ.
-- PT: Um domínio pequeno compartilhado pelos três estilos de API: um autor tem muitos livros, um
--     livro tem muitas resenhas. As duas chaves estrangeiras são as "leituras aninhadas" que fazem
--     os estilos se diferenciarem.
-- ES: Un dominio pequeño compartido por los tres estilos de API: un autor tiene muchos libros, un
--     libro tiene muchas reseñas. Las dos claves foráneas son las "lecturas anidadas" que hacen
--     que los estilos se diferencien.
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE authors (
	id      integer PRIMARY KEY,
	name    text NOT NULL,
	country text NOT NULL,
	bio     text NOT NULL
);

CREATE TABLE books (
	id        integer PRIMARY KEY,
	author_id integer NOT NULL REFERENCES authors (id),
	title     text NOT NULL,
	year      integer NOT NULL,
	pages     integer NOT NULL,
	isbn      text NOT NULL,
	summary   text NOT NULL
);

CREATE TABLE reviews (
	id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	book_id  integer NOT NULL REFERENCES books (id),
	rating   integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
	reviewer text NOT NULL,
	body     text NOT NULL
);

-- EN: Without these indexes every "books of this author" or "reviews of this book" lookup would
--     scan the whole table, and the benchmark would measure the missing index, not the API style.
-- PT: Sem estes índices cada busca de "livros deste autor" ou "resenhas deste livro" varreria a
--     tabela inteira, e o benchmark mediria o índice que falta, não o estilo de API.
-- ES: Sin estos índices cada búsqueda de "libros de este autor" o "reseñas de este libro" recorrería
--     la tabla completa, y el benchmark mediría el índice que falta, no el estilo de API.
CREATE INDEX books_author_id_idx ON books (author_id);
CREATE INDEX reviews_book_id_idx ON reviews (book_id);
