// EN: `bun run demo`: runs the scenarios against RabbitMQ and PostgreSQL, prints the tables and
//     rewrites `results/results.md`.
// PT: `bun run demo`: roda os cenários contra o RabbitMQ e o PostgreSQL, mostra as tabelas e
//     reescreve `results/results.md`.
// ES: `bun run demo`: ejecuta los escenarios contra RabbitMQ y PostgreSQL, imprime las tablas y
//     reescribe `results/results.md`.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadConfig } from "./core";
import { connectDb } from "./db";
import { connectBroker } from "./pipeline";
import { type DuplicatesResult, duplicatesScenario, type PoisonResult, poisonScenario } from "./scenarios";

export function renderReport(runs: DuplicatesResult[], poison: PoisonResult): string {
	const lines = [
		"# idempotency-dlq: results",
		"",
		"Generated by `docker compose run --rm demo`. Do not edit by hand.",
		"",
		"## Duplicated messages",
		"",
		"Every message is published twice, and the consumer drops the acknowledgement of 20% of the deliveries after applying the effect. Each message credits 1.00 to one account.",
		"",
		"| Consumer | Messages | Deliveries | Fewest deliveries of one message | Effects applied | Balance | Expected balance |",
		"| --- | --- | --- | --- | --- | --- | --- |",
	];
	for (const run of runs) {
		const wrong = run.effects !== run.messages;
		const effects = wrong ? `**${run.effects}**` : String(run.effects);
		const balance = (run.balanceCents / 100).toFixed(2);
		lines.push(
			`| \`${run.mode}\` | ${run.messages} | ${run.deliveries} | ${run.minDeliveriesPerMessage} | ${effects} | ${wrong ? `**${balance}**` : balance} | ${(run.expectedBalanceCents / 100).toFixed(2)} |`,
		);
	}
	lines.push(
		"",
		"## Poisoned message",
		"",
		`Retry policy: ${poison.policy.maxAttempts} attempts, exponential backoff starting at ${poison.policy.baseDelayMs} ms. The poisoned message fails on every attempt; ${poison.healthyMessages} healthy messages travel with it, and ${poison.effects} effects were applied.`,
		"",
		"| Attempt of the poisoned message | Waited since the previous attempt |",
		"| --- | --- |",
	);
	for (const attempt of poison.poisonAttempts) {
		lines.push(
			`| ${attempt.attempt} | ${attempt.waitedMs === null ? "first delivery" : `${Math.round(attempt.waitedMs)} ms`} |`,
		);
	}
	lines.push(
		"",
		"| Message in the dead-letter queue | Given up on attempt | Reason recorded by RabbitMQ |",
		"| --- | --- | --- |",
	);
	for (const letter of poison.deadLetters) {
		lines.push(`| \`${letter.messageId}\` | ${letter.attempt} | ${letter.reason} |`);
	}
	lines.push("");
	return lines.join("\n");
}

if (import.meta.main) {
	const config = loadConfig();
	const pool = await connectDb(config.DATABASE_URL);
	const connection = await connectBroker(config.AMQP_URL);
	const options = { messages: 1000, crashRate: 0.2, seed: 42 };
	const runs = [
		await duplicatesScenario(connection, pool, "naive", options),
		await duplicatesScenario(connection, pool, "idempotent", options),
	];
	const poison = await poisonScenario(connection, pool, { maxAttempts: 4, baseDelayMs: 200 });
	await connection.close();
	await pool.end();

	const report = renderReport(runs, poison);
	console.log(report);
	const resultsDir = join(config.PROJECT_DIR, "results");
	mkdirSync(resultsDir, { recursive: true });
	writeFileSync(join(resultsDir, "results.md"), report);
	console.log(`written to ${join(resultsDir, "results.md")}`);
}
