import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { type Bench, benchSchema } from "./bench";

// EN: Reads the JSON written by the TypeScript and the Rust benchmark and writes the timing
//     table in Markdown. The column to look at is the ratio between one difficulty and the
//     previous one, which should be close to 16.
// PT: Lê o JSON gravado pelos benchmarks em TypeScript e em Rust e escreve a tabela de tempos em
//     Markdown. A coluna a observar é a razão entre uma dificuldade e a anterior, que deve
//     ficar perto de 16.
function load(path: string): Bench | undefined {
	if (!existsSync(path)) {
		return undefined;
	}
	return benchSchema.parse(JSON.parse(readFileSync(path, "utf8")));
}

function format(value: number, digits: number): string {
	return value.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits });
}

function table(bench: Bench): string[] {
	const lines = [
		`### ${bench.language === "ts" ? "TypeScript" : "Rust"} (${bench.runtime})`,
		"",
		`Command: \`${bench.command}\``,
		"",
		"| Zero hex digits | Blocks mined | Expected attempts (16^d) | Mean attempts | Time per block, median (ms) | Fastest and slowest pass (ms) | Attempts ratio | Time ratio |",
		"| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
	];
	bench.rows.forEach((row, index) => {
		const previous = bench.rows[index - 1];
		const attemptsRatio = previous === undefined ? "-" : format(row.meanAttempts / previous.meanAttempts, 1);
		const timeRatio = previous === undefined ? "-" : format(row.medianMs / previous.medianMs, 1);
		const range = `${format(row.minMs, 4)} to ${format(row.maxMs, 4)}`;
		lines.push(
			`| ${row.difficulty} | ${format(row.blocks, 0)} | ${format(16 ** row.difficulty, 0)} | ${format(row.meanAttempts, 1)} | ${format(row.medianMs, 4)} | ${range} | ${attemptsRatio} | ${timeRatio} |`,
		);
	});
	lines.push("");
	return lines;
}

const dir = process.argv[2];
if (dir === undefined) {
	console.error("usage: bun run src/report.ts <results folder>");
	process.exit(2);
}
const benches = [load(join(dir, "mining-ts.json")), load(join(dir, "mining-rust.json"))].filter(
	(bench): bench is Bench => bench !== undefined,
);
const first = benches[0];
if (first === undefined) {
	console.error(`no mining-*.json found in ${dir}`);
	process.exit(1);
}

const lines = [
	"# Mining time by difficulty",
	"",
	"Generated by `./setup-unix-didactic-blockchain.sh bench` (or the `.ps1` script). Do not edit by hand.",
	"",
	`- Date: ${first.date}`,
	`- Machine (as seen from inside the container): ${first.machine}`,
	`- Each row mines the stated number of different block headers, on one thread, ${first.rows[0]?.passes ?? 1} times over. The time is the median pass divided by the number of blocks, with the fastest and the slowest pass next to it.`,
	"- The headers are fixed, so the number of attempts is the same on every run and in both languages. Only the time changes with the machine.",
	"- The TypeScript run discards a warm-up of 250 blocks at difficulty 3 first, so the just-in-time compiler does not inflate the first rows.",
	"- Timings are noisy: the machine was shared with other workloads. Read the ratios, not the absolute times.",
	"",
	"Each extra zero hexadecimal digit should multiply the work by about 16. The ratio columns divide a row by the row above it.",
	"",
	"At difficulty 1 a block needs only about 16 hashes, so the fixed cost of preparing each header is a visible share of the time and the first time ratio falls below 16. From difficulty 2 on, hashing dominates and the time ratio follows the attempts ratio.",
	"",
	...benches.flatMap(table),
];

const [ts, rust] = [benches.find((b) => b.language === "ts"), benches.find((b) => b.language === "rust")];
if (ts !== undefined && rust !== undefined) {
	const same = ts.rows.every((row, index) => row.attempts === rust.rows[index]?.attempts);
	lines.push(
		"### Cross-check",
		"",
		same
			? "TypeScript and Rust tried exactly the same number of nonces at every difficulty, which shows that both compute the same hashes."
			: "WARNING: TypeScript and Rust tried a different number of nonces. The two implementations disagree.",
		"",
	);
	if (!same) {
		console.error("attempts differ between TypeScript and Rust");
		process.exitCode = 1;
	}
}

writeFileSync(join(dir, "mining.md"), lines.join("\n"));
console.log(lines.join("\n"));
