// EN: `bun run demo`: runs the RabbitMQ experiments and the in-process backpressure experiment,
//     prints the tables and rewrites `results/results.md`.
// PT: `bun run demo`: roda os experimentos com RabbitMQ e o experimento de backpressure em
//     processo, mostra as tabelas e reescreve `results/results.md`.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DEFAULT_PRESSURE, type PressureResult, runPressure } from "./backpressure";
import {
	connectBroker,
	type DeliveryResult,
	fanOut,
	loadConfig,
	type PrefetchResult,
	prefetchExperiment,
	workQueue,
} from "./rabbit";

export interface Report {
	work: DeliveryResult;
	fan: DeliveryResult;
	combined: DeliveryResult;
	prefetch: PrefetchResult[];
	pressure: PressureResult[];
}

function deliveryRow(name: string, queues: number, result: DeliveryResult): string {
	const counts = result.perConsumer.map((received) => received.length).join(", ");
	return `| ${name} | ${queues} | ${result.perConsumer.length} | ${result.messages} | ${counts} | ${result.totalDeliveries} |`;
}

const capacityName = (capacity: number): string =>
	Number.isFinite(capacity) ? `bounded queue, capacity ${capacity}` : "unbounded queue";

export function renderReport(report: Report): string {
	const lines = [
		"# pubsub-backpressure: results",
		"",
		"Generated by `docker compose run --rm demo`. Do not edit by hand.",
		"",
		"## Work queue against fan-out (RabbitMQ)",
		"",
		"| Topology | Queues | Consumers | Messages published | Received by each consumer | Total deliveries |",
		"| --- | --- | --- | --- | --- | --- |",
		deliveryRow("Work queue: one queue, competing consumers", 1, report.work),
		deliveryRow("Fan-out: one queue per subscriber", report.fan.perConsumer.length, report.fan),
		deliveryRow("Fan-out to 2 services, 3 instances each", 2, report.combined),
		"",
		"## Where the backlog lives (RabbitMQ prefetch)",
		"",
		"A queue starts with a backlog of 1 KiB messages and one consumer that takes 2 ms per message, observed for 600 ms.",
		"",
		"| Prefetch | Backlog | Most messages held by the consumer at once | Left in the broker | Processed |",
		"| --- | --- | --- | --- | --- |",
	];
	for (const run of report.prefetch) {
		lines.push(
			`| ${run.prefetch === 0 ? "no limit" : run.prefetch} | ${run.backlog} | ${run.peakHeldByConsumer} | ${run.leftInBroker} | ${run.processed} |`,
		);
	}
	lines.push(
		"",
		"## Producer faster than consumer, in one process",
		"",
		`The producer tries to send ${DEFAULT_PRESSURE.burst} messages of ${DEFAULT_PRESSURE.payloadBytes} bytes per millisecond; the consumer handles one per millisecond.`,
		"",
		"| Buffer | Produced | Consumed | Peak messages waiting | Growth of process memory (RSS) |",
		"| --- | --- | --- | --- | --- |",
	);
	for (const run of report.pressure) {
		lines.push(
			`| ${capacityName(run.capacity)} | ${run.produced} | ${run.consumed} | ${run.peakBuffered} | ${run.rssGrowthMb.toFixed(1)} MiB |`,
		);
	}
	lines.push("", "Memory over time (messages waiting, and MiB waiting in the buffer):", "");
	const header = report.pressure.map((run) => `${capacityName(run.capacity)} |`).join(" ");
	lines.push(`| Time | ${header}`, `| --- |${report.pressure.map(() => " --- |").join("")}`);
	const rows = Math.min(...report.pressure.map((run) => run.samples.length));
	for (let index = 0; index < rows; index += 4) {
		const cells = report.pressure.map((run) => {
			const sample = run.samples[index];
			return sample === undefined ? "" : `${sample.buffered} (${sample.bufferedMb.toFixed(1)} MiB)`;
		});
		lines.push(`| ${report.pressure[0]?.samples[index]?.atMs ?? 0} ms | ${cells.join(" | ")} |`);
	}
	lines.push("");
	return lines.join("\n");
}

if (import.meta.main) {
	const config = loadConfig();
	// EN: The bounded run goes first: both share this process, and measuring it after the
	//     unbounded run would only show that run's buffer being freed.
	// PT: A execução limitada vai primeiro: as duas dividem este processo, e medi-la depois da
	//     ilimitada só mostraria o buffer da outra sendo liberado.
	const bounded = await runPressure({ ...DEFAULT_PRESSURE, capacity: 100 });
	const unbounded = await runPressure({ ...DEFAULT_PRESSURE, capacity: Number.POSITIVE_INFINITY });
	const connection = await connectBroker(config.AMQP_URL);
	const report: Report = {
		work: await workQueue(connection, 300, 3),
		fan: await fanOut(connection, 300, 3),
		combined: await fanOut(connection, 300, 2, 3),
		prefetch: [await prefetchExperiment(connection, 0, 3000), await prefetchExperiment(connection, 10, 3000)],
		pressure: [unbounded, bounded],
	};
	await connection.close();

	const text = renderReport(report);
	console.log(text);
	const resultsDir = join(config.PROJECT_DIR, "results");
	mkdirSync(resultsDir, { recursive: true });
	writeFileSync(join(resultsDir, "results.md"), text);
	console.log(`written to ${join(resultsDir, "results.md")}`);
}
