-- EN: The one schema shared by the three approaches. It is plain SQL on purpose: the tables are
--     created once, here, and Prisma and Drizzle only describe tables that already exist. That
--     way the comparison is about how each tool queries, not about how each tool migrates.
-- PT: O único schema, compartilhado pelas três abordagens. É SQL puro de propósito: as tabelas
--     são criadas uma vez, aqui, e Prisma e Drizzle só descrevem tabelas que já existem. Assim a
--     comparação é sobre como cada ferramenta consulta, não sobre como cada uma migra.
-- ES: El único schema, compartido por los tres enfoques. Es SQL puro a propósito: las tablas se crean
--     una vez, aquí, y Prisma y Drizzle solo describen tablas que ya existen. Así la comparación
--     trata de cómo consulta cada herramienta, no de cómo migra cada una.
DROP TABLE IF EXISTS comments, posts, authors;

CREATE TABLE authors (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL,
	country text NOT NULL
);

CREATE TABLE posts (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	author_id integer NOT NULL REFERENCES authors (id) ON DELETE CASCADE,
	title text NOT NULL,
	views integer NOT NULL DEFAULT 0,
	published boolean NOT NULL DEFAULT false
);

-- EN: The length check exists so that a test can make the second INSERT of a transaction fail
--     and prove that the first one is rolled back.
-- PT: A checagem de tamanho existe para um teste conseguir fazer o segundo INSERT de uma
--     transação falhar e provar que o primeiro é desfeito.
-- ES: La verificación de tamaño existe para que una prueba pueda hacer fallar el segundo INSERT de una
--     transacción y demostrar que el primero se deshace.
CREATE TABLE comments (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	post_id integer NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
	body text NOT NULL CHECK (char_length(body) <= 200)
);

-- EN: Foreign keys are not indexed automatically in PostgreSQL. Without these two indexes every
--     "posts of this author" lookup would scan the whole table.
-- PT: Chaves estrangeiras não são indexadas automaticamente no PostgreSQL. Sem estes dois índices,
--     toda busca "posts deste autor" varreria a tabela inteira.
-- ES: Las claves foráneas no se indexan automáticamente en PostgreSQL. Sin estos dos índices,
--     toda búsqueda de "posts de este autor" recorrería la tabla entera.
CREATE INDEX posts_author_id_idx ON posts (author_id);
CREATE INDEX comments_post_id_idx ON comments (post_id);

-- EN: Deterministic fake data: 200 authors, 1 to 7 posts each, 2 comments per post.
-- PT: Dados falsos e determinísticos: 200 autores, de 1 a 7 posts cada, 2 comentários por post.
-- ES: Datos falsos y determinísticos: 200 autores, de 1 a 7 posts cada uno, 2 comentarios por post.
INSERT INTO authors (id, name, country)
SELECT i, 'Fake Author ' || lpad(i::text, 3, '0'), (ARRAY['BR', 'US', 'PT', 'JP'])[1 + i % 4]
FROM generate_series(1, 200) AS i;

INSERT INTO posts (author_id, title, views, published)
SELECT a.id, 'Post ' || a.id || '-' || j, (a.id * 37 + j * 101) % 1000, (a.id + j) % 3 <> 0
FROM authors a
CROSS JOIN LATERAL generate_series(1, 1 + a.id % 7) AS j
ORDER BY a.id, j;

INSERT INTO comments (post_id, body)
SELECT p.id, 'Fake comment ' || k || ' on post ' || p.id
FROM posts p
CROSS JOIN generate_series(1, 2) AS k
ORDER BY p.id, k;

SELECT setval(pg_get_serial_sequence('authors', 'id'), (SELECT max(id) FROM authors));
