# Documentation (English)

This page was edited by hand on a demonstration branch.

The real page is generated by `bun run docs:index` from the content of the repository. The step
"Documentation index is up to date" generates it again in memory, compares it with the committed
file and fails when they differ, which is what happens here.
