// EN: `docker compose run --rm demo`. Sends the same four checkouts to the JSON variant and to
//     the text variant, then asks the same question of both: "show me every log line of the
//     first request". It prints the answers and rewrites results/results.md.
// PT: `docker compose run --rm demo`. Manda os mesmos quatro checkouts para a variante JSON e
//     para a variante em texto, e depois faz a mesma pergunta às duas: "mostre todas as linhas
//     de log da primeira requisição". Imprime as respostas e reescreve results/results.md.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readLabEnv } from "./config";
import { CHECKOUTS, jsonQuery, LINES_PER_REQUEST, type LogLine, queryLoki, runScenario, textQuery } from "./lab";

const env = readLabEnv();
const scenario = await runScenario(env);
const jsonRequest = scenario.json[0];
const textRequest = scenario.text[0];
if (jsonRequest === undefined || textRequest === undefined) {
	throw new Error("the scenario sent no request");
}

interface Search {
	title: string;
	query: string;
	lines: LogLine[];
	verdict: string;
}

async function search(title: string, query: string, verdict: (lines: LogLine[]) => string): Promise<Search> {
	const lines = await queryLoki(env.LOKI_URL, query, scenario.sinceMs);
	return { title, query, lines, verdict: verdict(lines) };
}

const services = (lines: LogLine[]): string => [...new Set(lines.map((line) => line.service))].join(", ");

const searches = [
	await search(
		"Structured (JSON): by correlation id",
		jsonQuery(jsonRequest.correlationId),
		(lines) => `${lines.length} of ${LINES_PER_REQUEST} lines of the request, from ${services(lines)}. Complete.`,
	),
	await search(
		"Unstructured (text): by order id, the only id the sentences have",
		textQuery(textRequest.orderId),
		(lines) =>
			`${lines.length} of ${LINES_PER_REQUEST} lines of the request, from ${services(lines)}. The sentences that do not mention the order are missing.`,
	),
	await search(
		"Unstructured (text): by customer name, to reach the missing sentences",
		textQuery(textRequest.customer),
		(lines) =>
			`${lines.length} lines, from ${services(lines)}. They belong to ${CHECKOUTS.filter((checkout) => checkout.customer === textRequest.customer).length} different requests of ${textRequest.customer}, and nothing in the lines says which is which.`,
	),
];

const block = (item: Search): string =>
	[
		`### ${item.title}`,
		"",
		"```logql",
		item.query,
		"```",
		"",
		"```text",
		...item.lines.map((line) => line.line),
		"```",
		"",
		item.verdict,
		"",
	].join("\n");

const report = [
	"# structured-logs: the same search on both variants",
	"",
	"Generated by `docker compose run --rm demo`. Ids and timestamps change on every run.",
	"",
	`Both variants received the same ${CHECKOUTS.length} concurrent checkouts, and each request wrote ${LINES_PER_REQUEST} log lines (2 in each of api, orders and worker).`,
	`The question is the same for both: show every log line of the first request (${jsonRequest.customer}, ${CHECKOUTS[0].qty} x ${CHECKOUTS[0].sku}).`,
	"",
	...searches.map(block),
].join("\n");

console.log(report);
const resultsDir = join(env.PROJECT_DIR, "results");
mkdirSync(resultsDir, { recursive: true });
writeFileSync(join(resultsDir, "results.md"), report);
console.log(`written to ${join(resultsDir, "results.md")}`);
