// EN: `bun run docs:index [--check]` writes `docs/en/README.md` and `docs/pt/README.md` from
//     the repository itself: areas, question counts, blind reviews and mini-projects. A status
//     page written by hand goes stale on the next merge, so this one is generated, and
//     `--check` fails in CI when the committed pages no longer match.
// PT: `bun run docs:index [--check]` escreve `docs/en/README.md` e `docs/pt/README.md` a partir
//     do próprio repositório: áreas, contagem de questões, revisões cegas e mini-projetos. Uma
//     página de status escrita à mão fica velha no próximo merge, então esta é gerada, e
//     `--check` falha no CI quando as páginas versionadas já não batem.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { checkContent, loadAreas, loadMiniProjects } from "../src/content/check";
import type { Language } from "../src/content/schema";

const repoRoot = resolve(import.meta.dir, "..", "..");
const contentDir = join(repoRoot, "quiz", "content");

const TEXT = {
	en: {
		title: "# Documentation (English)",
		other: "> Versão em português: [docs/pt](../pt/README.md)",
		intro: "Documentation is organised by area. Every page here has an equivalent page under `docs/pt/`. This page is generated by `bun run docs:index`: do not edit it by hand.",
		guides: "## Guides",
		guideList: [
			["../../REFERENCES.md", "Study references for every area"],
			["decisions.md", "Project decisions"],
			["quiz.md", "Quiz design"],
			["quiz-authoring.md", "How to write quiz questions"],
			["mini-project-catalog.md", "Mini-project catalog"],
			["environment.md", "Environment: pinned Docker images and formatters"],
			["benchmarks.md", "Benchmark contract and runner"],
			["brainstorming.md", "Brainstorming record"],
		],
		status: "## Status by area",
		totals: (questions: number, target: number, done: number, all: number) =>
			`${questions} of ${target} questions written, ${done} of ${all} mini-projects done. The roadmap is [PLAN.md](../../PLAN.md).`,
		head: "| Area | Kind | Questions | Blind review | Mini-projects |",
		kind: { "theory-only": "Theory", "theory-and-practice": "Theory and practice" },
		reviewed: "done",
		pending: "pending",
		none: "none",
		planned: "planned",
	},
	pt: {
		title: "# Documentação (Português)",
		other: "> English version: [docs/en](../en/README.md)",
		intro: "A documentação é organizada por área. Toda página aqui tem uma página equivalente em `docs/en/`. Esta página é gerada por `bun run docs:index`: não edite à mão.",
		guides: "## Guias",
		guideList: [
			["../../REFERENCES.pt-BR.md", "Referências de estudo de cada área"],
			["decisions.md", "Decisões do projeto"],
			["quiz.md", "Desenho do quiz"],
			["quiz-authoring.md", "Como escrever questões do quiz"],
			["mini-project-catalog.md", "Catálogo de mini-projetos"],
			["environment.md", "Ambiente: imagens Docker fixadas e formatadores"],
			["benchmarks.md", "Contrato e runner de benchmark"],
			["brainstorming.md", "Registro do brainstorming"],
		],
		status: "## Status por área",
		totals: (questions: number, target: number, done: number, all: number) =>
			`${questions} de ${target} questões escritas, ${done} de ${all} mini-projetos prontos. O roteiro é o [PLAN.md](../../PLAN.md).`,
		head: "| Área | Tipo | Questões | Revisão cega | Mini-projetos |",
		kind: { "theory-only": "Teoria", "theory-and-practice": "Teoria e prática" },
		reviewed: "feita",
		pending: "pendente",
		none: "nenhum",
		planned: "planejado",
	},
} as const;

function render(language: Language): string {
	const text = TEXT[language];
	const areas = loadAreas(contentDir);
	const miniProjects = loadMiniProjects(contentDir);
	const counts = new Map(checkContent({ contentDir, repoRoot }).areas.map((area) => [area.area, area.actual]));

	const rows = areas.map((area) => {
		const count = counts.get(area.slug) ?? 0;
		const reviewed = existsSync(join(contentDir, area.slug, "review.md"));
		const projects = miniProjects
			.filter((item) => item.area === area.slug)
			.map((item) => {
				const name = basename(item.path);
				// EN: A finished mini-project links to its documentation page, when there is one.
				// PT: Um mini-projeto pronto aponta para sua página de documentação, quando existe.
				const page = join(repoRoot, "docs", language, area.slug, `${name}.md`);
				if (item.status !== "done") {
					return `${name} (${text.planned})`;
				}
				return existsSync(page) ? `[${name}](${area.slug}/${name}.md)` : `[${name}](../../${item.path})`;
			});
		const review = count === 0 ? "" : reviewed ? text.reviewed : text.pending;
		return `| ${area.name[language]} | ${text.kind[area.kind]} | ${count}/${area.target} | ${review} | ${projects.join(", ") || text.none} |`;
	});

	const questions = [...counts.values()].reduce((sum, value) => sum + value, 0);
	const target = areas.reduce((sum, area) => sum + area.target, 0);
	const done = miniProjects.filter((item) => item.status === "done").length;
	return [
		text.title,
		"",
		text.other,
		"",
		text.intro,
		"",
		text.guides,
		"",
		...text.guideList.map(([file, label]) => `- [${label}](${file})`),
		"",
		text.status,
		"",
		text.totals(questions, target, done, miniProjects.length),
		"",
		text.head,
		"| --- | --- | ---: | --- | --- |",
		...rows,
		"",
	].join("\n");
}

const check = process.argv.includes("--check");
let stale = false;
for (const language of ["en", "pt"] as const) {
	const file = join(repoRoot, "docs", language, "README.md");
	const content = render(language);
	if (check) {
		if (readFileSync(file, "utf8") !== content) {
			console.error(`${file} is out of date: run "bun run docs:index"`);
			stale = true;
		}
	} else {
		writeFileSync(file, content);
		console.log(`wrote ${file}`);
	}
}
process.exit(stale ? 1 : 0);
