// EN: Runs one incident and writes its timeline to results/. k6 starts with this container
//     (see docker-compose.yml): a quiet period, one minute of overload, then quiet again.
// PT: Roda um incidente e grava a linha do tempo em results/. O k6 sobe junto com este
//     contêiner (veja docker-compose.yml): um período calmo, um minuto de sobrecarga, e calma
//     de novo.
// ES: Ejecuta un incidente y graba la línea de tiempo en results/. k6 arranca junto con este
//     contenedor (ve docker-compose.yml): un período tranquilo, un minuto de sobrecarga, y calma
//     otra vez.

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { AVAILABILITY, budgetSpent, hoursToExhaustion, LATENCY } from "./slo";
import {
	ALERTS,
	type AlertTimeline,
	readLabEnv,
	secondsBetween,
	type Timeline,
	waitReady,
	watchIncident,
} from "./watch";

const env = readLabEnv();
await Promise.all([
	waitReady(`${env.PROMETHEUS_URL}/-/ready`, 120_000),
	waitReady(`${env.ALERTMANAGER_URL}/-/ready`, 120_000),
	waitReady(`${env.SHOP_URL}/health`, 120_000),
]);

console.log("watching: normal traffic now, k6 overload in about 45 seconds\n");
const timeline: Timeline = await watchIncident(env, 420_000, console.log);

const fmt = (value: number | undefined, digits = 0): string =>
	value === undefined ? "did not happen" : value.toFixed(digits);
const row = (label: string, entry: AlertTimeline): string =>
	`| ${label} | ${fmt(secondsBetween(timeline.loadStartedAt, entry.pendingAt))} | ${fmt(secondsBetween(timeline.loadStartedAt, entry.firingAt))} | ${fmt(secondsBetween(timeline.loadStartedAt, entry.notifiedAt))} | ${fmt(secondsBetween(timeline.loadStoppedAt, entry.resolvedAt))} | ${fmt(secondsBetween(timeline.loadStoppedAt, entry.resolvedNotifiedAt))} | ${fmt(entry.peakBurnRate, 1)} | ${fmt(entry.longWindowBurnAtResolve, 1)} |`;

const peak = timeline.availability.peakBurnRate;
const report = `# slo-alert: an objective becomes an alert

Generated by \`docker compose run --rm demo\`. Load: \`grafana/k6\` with 30 virtual users on \`GET /pay\` for 60 seconds, against a shop that serves 8 requests at a time. Normal traffic of about 5 requests per second runs before, during and after.

| Measured | Value |
| --- | --- |
| Peak request rate | ${fmt(timeline.peakRequestsPerSecond)} requests per second |
| Load lasted | ${fmt(secondsBetween(timeline.loadStartedAt, timeline.loadStoppedAt))} s |
| Peak share of failed requests (1-minute window) | ${(timeline.peakErrorRatio * 100).toFixed(1)}% (objective: at most ${((1 - AVAILABILITY.objective) * 100).toFixed(0)}%) |
| Peak share of slow successful requests (1-minute window) | ${(timeline.peakSlowRatio * 100).toFixed(1)}% (objective: at most ${((1 - LATENCY.objective) * 100).toFixed(0)}%) |
| Alert pending or firing before the load | ${timeline.alertBeforeLoad ? "yes" : "no"} |
| Availability error budget left, measured over the last hour | ${fmt(timeline.budgetRemainingAtEnd, 2)} (1 = untouched, below 0 = overspent) |

## Timeline of the two alerts

Seconds are counted from the moment the watcher saw the load start (first three columns) or stop (the next two).

| Alert | Pending after | Firing after | Receiver notified after | Resolved after the load stopped | Receiver told "resolved" after | Peak burn rate (1 m) | Burn rate of the 5 m window at resolution |
| --- | --- | --- | --- | --- | --- | --- | --- |
${row(ALERTS.availability.name, timeline.availability)}
${row(ALERTS.latency.name, timeline.latency)}

## Reading the numbers

- A burn rate of ${fmt(peak, 1)} means the availability budget of 30 days would be gone in ${fmt(hoursToExhaustion(peak), 1)} hours at that pace. One minute of it spends ${(budgetSpent(peak, 1 / 60) * 100).toFixed(2)}% of the 30-day budget.
- The alerts resolved while the 5-minute window was still far above its threshold (last column). The 1-minute window had dropped, and the rule needs both. With the long window alone, the page would have stayed on for about five minutes after the service recovered.
- Thresholds: availability pages above a burn rate of ${AVAILABILITY.burnRateThreshold}, latency above ${LATENCY.burnRateThreshold}, in both windows, held for 10 seconds (\`for\`).
`;

const resultsDir = join(env.PROJECT_DIR, "results");
mkdirSync(resultsDir, { recursive: true });
// EN: Remove before writing: a file left by a run under another user could not be overwritten.
// PT: Remove antes de gravar: um arquivo deixado por uma execução de outro usuário não poderia
//     ser sobrescrito.
// ES: Elimina antes de grabar: un archivo dejado por una ejecución de otro usuario no podría
//     sobrescribirse.
for (const [name, content] of [
	["results.md", report],
	["timeline.json", `${JSON.stringify(timeline, null, "\t")}\n`],
] as const) {
	rmSync(join(resultsDir, name), { force: true });
	writeFileSync(join(resultsDir, name), content);
}
console.log(`\n${report}`);
