// EN: Turns the measurements into the Markdown committed in `results/results.md`. A benchmark
//     without the machine, the versions and the command cannot be reproduced, so they are part
//     of the report.
// PT: Transforma as medições no Markdown versionado em `results/results.md`. Um benchmark sem a
//     máquina, as versões e o comando não pode ser reproduzido, então eles fazem parte do
//     relatório.
// ES: Convierte las mediciones en el Markdown versionado en `results/results.md`. Un benchmark sin
//     la máquina, las versiones y el comando no puede reproducirse, así que forman parte del
//     reporte.

import type { OrderingResult, RedeliveryResult, Spread, ThroughputResult } from "./experiments";
import type { BrokerName } from "./queue";

export interface BrokerResult {
	broker: BrokerName;
	ordering: OrderingResult;
	redelivery: RedeliveryResult;
	throughput: ThroughputResult;
}

export interface Environment {
	date: string;
	cpu: string;
	cores: number;
	memoryGb: number;
	kernel: string;
	bun: string;
	images: Record<BrokerName, string>;
	clients: Record<BrokerName, string>;
	command: string;
}

const NAMES: Record<BrokerName, string> = {
	bullmq: "BullMQ on Redis",
	rabbitmq: "RabbitMQ",
	kafka: "Kafka",
	sqs: "SQS on LocalStack",
};

const yesNo = (value: boolean): string => (value ? "yes" : "**no**");
const whole = (value: number): string => Math.round(value).toLocaleString("en-US");
const rate = (value: Spread): string => `${whole(value.mean)} (${whole(value.min)} to ${whole(value.max)})`;

function flag(value: boolean | null): string {
	if (value === null) {
		return "none";
	}
	return value ? "flagged as redelivered" : "not flagged";
}

export function renderReport(results: BrokerResult[], environment: Environment): string {
	const lines: string[] = [
		"# queue-comparison: results",
		"",
		`Generated by \`${environment.command}\` on ${environment.date}. Do not edit by hand.`,
		"",
		"## Behaviour experiments",
		"",
		"Ordering: orders sent in sequence, one consumer handling one message at a time. Kafka uses a topic with 3 partitions and the customer id as key; the other brokers use one queue. Redelivery: a consumer process is killed with SIGKILL after receiving the message and before acknowledging it.",
		"",
		"| Broker | Received in the order sent | In order per customer (key) | Out-of-order messages | Redelivered after the crash | Delay until redelivery | Signal from the broker |",
		"| --- | --- | --- | --- | --- | --- | --- |",
	];
	for (const { broker, ordering, redelivery } of results) {
		const delay = redelivery.afterMs === null ? "n/a" : `${(redelivery.afterMs / 1000).toFixed(1)} s`;
		lines.push(
			`| ${NAMES[broker]} | ${yesNo(ordering.globalOrder)} | ${yesNo(ordering.perKeyOrder)} | ${ordering.outOfOrder} of ${ordering.messages} | ${yesNo(redelivery.redelivered)} | ${delay} | ${flag(redelivery.brokerFlag)} |`,
		);
	}
	const first = results[0];
	lines.push(
		"",
		"## Throughput",
		"",
		first === undefined
			? "No broker measured."
			: `${whole(first.throughput.messages)} messages per run, ${first.throughput.runs} measured runs after one discarded warm-up run. Messages per second: mean (lowest run to highest run). Producing finishes before consuming starts.`,
		"",
		"| Broker | Produce, msg/s | Consume, msg/s |",
		"| --- | --- | --- |",
	);
	for (const { broker, throughput } of results) {
		lines.push(`| ${NAMES[broker]} | ${rate(throughput.produce)} | ${rate(throughput.consume)} |`);
	}
	lines.push(
		"",
		"## Environment",
		"",
		`- Machine: ${environment.cpu}, ${environment.cores} logical cores, ${environment.memoryGb.toFixed(1)} GiB visible to Docker, kernel ${environment.kernel}`,
		`- Runtime: Bun ${environment.bun}`,
		"",
		"| Broker | Image | Client library |",
		"| --- | --- | --- |",
	);
	for (const { broker } of results) {
		lines.push(`| ${NAMES[broker]} | \`${environment.images[broker]}\` | ${environment.clients[broker]} |`);
	}
	lines.push("");
	return lines.join("\n");
}
